name: deviceplane-agent
base: core20
version: '0.1'
summary: Deviceplane is the simplest way to access and manage remote fleets.
description: |
 Deviceplane is an open source device management tool for embedded systems and edge computing. 
 It solves various infrastructure problems related to remote device management such as:
 - Network connectivity and SSH access
 - Orchestration and deployment of remote updates
 - Host and application monitoring
 - Device organization: naming, labeling, searching, and filtering of devices
 - Access and security controls

grade: stable
confinement: strict

parts:
  deviecplace-src:
    # See 'snapcraft plugins'
    source: https://github.com/deviceplane/deviceplane
    source-type: git
    plugin: go
      
apps:
  deviceplane-agent:
    command: bin/agent
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - greengrass-support
  
  agent:
    command: bin/agent  
    plugs:
      - network
      - network-bind
      - network-control
      - greengrass-support
